<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>quote tool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script src="/components/internal_tools/netsuite/quote_tool/js/jquery.editable.js"></script>
    <script src="/components/internal_tools/netsuite/quote_tool/js/list.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    
    <link rel="stylesheet" href="/components/internal_tools/netsuite/quote_tool/css/main.css?20150316">
</head>
<body>
    <div class="container" style="padding-top:20px;">
        <!-- sales & customer info -->
        <div class="panel">
            <div class="panel-heading">Customer information</div>
            <div class="panel-body">
                <form action="" class="quote-form form-horizontal">
                    <div class="form-group">
                        <div class="nopdf">
                            <label for="" class="control-label col-sm-2">
                                Customer ID
                            </label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="customer_id" name="customer_id" value="<?php echo $customerInfo['customer_id'];?>">
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Customer Address</label>
                            <div class="col-sm-9">
                                <textarea maxlength="256" name="customer_addr" id="customer_addr" name="customer_addr" rows="6" class="form-control required"><?php echo $customerInfo['customer_addr'];?></textarea>
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Contact Name</label>
                            <div class="col-sm-3">
                                <input type="text" maxlength="48" class="form-control required" id="customer_name" name="customer_name" value="<?php echo $customerInfo['customer_name'];?>">
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                        <div class="">
                            <label for="" class="control-label col-sm-2">Currency</label>
                            <div class="col-sm-3">
                                <select name="customer_currency" id="customer_currency" class="form-control">
                                <?php
                                foreach ($currenciesSupported as $_currency => $_val) {
                                ?>
                                    <option value="<?php echo $_currency;?>"<?php echo !strcasecmp ($customerInfo['customer_currency'], $_currency) ? ' selected' : '';?>><?php echo $_val;?></option>
                                <?php
                                }
                                ?>
                                </select>
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Phone</label>
                            <div class="col-sm-3">
                                <input type="text" maxlength="32" class="form-control required" id="customer_phone"  name="customer_phone" value="<?php echo $customerInfo['customer_phone'];?>">
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                        <div class="">
                            <label for="" class="control-label col-sm-2">
                                Language
                            </label>
                            <div class="col-sm-3">
                                <select name="customer_language" id="customer_language" class="form-control">
                                <?php
                                foreach ($languagesSupported as $_lang => $_val) {
                                ?>
                                    <option value="<?php echo $_val;?>"<?php echo !strcasecmp ($customerInfo['customer_language'], $_val) ? ' selected' : '';?>><?php echo $_lang;?></option>
                                <?php
                                }
                                ?>
                                </select>
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Email</label>
                            <div class="col-sm-3">
                                <input type="text" maxlength="32" class="form-control required" id="customer_email" name="customer_email" value="<?php echo $customerInfo['customer_email'];?>">
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                        <div class="">
                            <label for="" class="control-label col-sm-2">Price Level</label>
                            <div class="col-sm-3">
                                <select name="customer_level" id="customer_level" class="form-control">
                                <?php
                                foreach ($priceLevels as $_level => $_val) {
                                ?>
                                    <option value="<?php echo $_level;?>"<?php echo $customerInfo['customer_level'] == $_level ? ' selected' : '';?>><?php echo $_val;?></option>
                                <?php
                                }
                                ?>
                                </select>
                            </div>
                            <div class="error col-sm-1 invisiable">
                                <i class="fa fa-close"></i>
                            </div>
                        </div>
                    </div>                
                </form>
            </div>
        </div>
        
        <!-- item builder -->
        <div class="panel">
            <!-- <div class="panel-heading">item builder</div> -->
            <table class="quote-builder table">
                <thead>
                    <tr>
                        <th class="item">Type</th>
                        <th>Model</th>
                        <th>Interface</th>
                        <th>Capacity</th>
                        <th>Color</th>
                        <th>Unit Price</th>
                        <th>Tax Rate</th>
                        <th>Quantity</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="items">
                    <tr class="item-row">
                        <td class="type">
                            <select name="type" id="" class="form-control">
                                <option value="<?php echo QuoteFormItem :: TYPE_MODEL;?>">Model</option>
                                <option value="<?php echo QuoteFormItem :: TYPE_ACCESSORY;?>">Accessory</option>
                                <option value="<?php echo QuoteFormItem :: TYPE_SERVICE;?>">Service</option>
                            </select>
                        </td>
                        <td class="model">
                            <select name="code" id="" class="form-control">
                            </select>
                        </td>
                        <td class="interface">
                            <select name="interface" id="" class="form-control">
                            </select>
                        </td>
                        <td class="capacity">
                            <select name="capacity" id="" class="form-control">
                            </select>
                        </td>
                        <td class="color">
                            <select name="color" id="" class="form-control">
                            </select>
                        </td>
                        <td class="price" data-pattern="^(\d+)(\.\d+)?$">
                            <input type="text" class="form-control required" name="unitPrice" placeholder="4.50">
                        </td>
                        <td class="taxRate">
                            <input type="text" class="form-control" name="taxRate" placeholder="15%">
                        </td>
                        <td class="price" data-pattern="^(\d+)(\.\d+)?$">
                            <input type="text" class="form-control required" name="qty" placeholder="500">
                        </td>
                        <td class="operations">
                            <a href="#" class="glyphicon glyphicon-plus" data-action="add"></a>
                            <a href="#" class="glyphicon glyphicon-trash" data-action="remove"></a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <!-- item template -->
            <table id="item-tpl" class="hide">
                <tr class="item-row">
                    <td class="type">
                        <select name="type" id="" class="form-control">
                            <option value="<?php echo QuoteFormItem :: TYPE_MODEL;?>">Model</option>
                            <option value="<?php echo QuoteFormItem :: TYPE_ACCESSORY;?>">Accessory</option>
                            <option value="<?php echo QuoteFormItem :: TYPE_SERVICE;?>">Service</option>
                        </select>
                    </td>
                    <td class="model">
                        <select name="code" id="" class="form-control">
                        </select>
                    </td>
                    <td class="interface">
                        <select name="interface" id="" class="form-control">
                        </select>
                    </td>
                    <td class="capacity">
                        <select name="capacity" id="" class="form-control">
                        </select>
                    </td>
                    <td class="color">
                        <select name="color" id="" class="form-control">
                        </select>
                    </td>
                    <td class="price" data-pattern="^(\d+)(\.\d+)?$">
                        <input type="text" class="form-control required" name="unitPrice" placeholder="4.50">
                    </td>
                    <td class="taxRate">
                        <input type="text" class="form-control required" name="taxRate" placeholder="15%">
                    </td>
                    <td class="price" data-pattern="^(\d+)(\.\d+)?$">
                        <input type="text" class="form-control required" name="qty" placeholder="500">
                    </td>
                    <td class="operations">
                        <a href="#" class="glyphicon glyphicon-plus" data-action="add"></a>
                        <a href="#" class="glyphicon glyphicon-trash" data-action="remove"></a>
                    </td>
                </tr>
            </table>
        </div>

        <div class="quote-footer">
            <a href="#" id="generatePDF" class="btn btn-primary btn-lg btn-generate">Generate PDF</a>
        </div>
    </div>
    <div id="warningDialog" class="modal fade in">
        <div class="modal-backdrop fade in" style="height: 100%;"></div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="border-bottom: 0;">
                    <button type="button" class="close">&times;</button>
                </div>
                <div class="modal-body">
                    <i class="fa fa-exclamation-triangle" style="font-size: 20px; color: orange; margin: 0 5px;"></i>
                    <span id="warning-txt">One or more fields are empty.</span>
                </div>
                <div class="modal-footer" style="border-top: 0;">
                    <button type="button" class="btn btn-primary">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        var items = <?php echo json_encode ($json);?>;
        var candidates = <?php echo json_encode ($candidateCustomerInfos);?>;//for autocomplete
        function updateOptions (index)
        {
            var currentRow = $($('#items .item-row')[index]);
            var type = $('.type > select', currentRow);
            var model= $('.model > select', currentRow);

            //productType: model/accessory/service
            if (type.val ()) {
                var options = '';
                for (var item_code in items[type.val ()]) {
                    var value = items[type.val ()][item_code]['name'];
                    if (2 == type.val ()) {
                        value = items.translations[value];
                    }
                    options += '<option value="' + item_code + '"' + (item_code == model.val () ? ' selected' : '') + '>' + value + '</option>';
                }
                model.html (options);
            }
            //capacity type:USB2.0/USB3.0
            var isModel = 0 == type.val ();
            var USBInterface = $('.interface > select', currentRow);
            if (isModel) {
                var options = '';
                for (var USBType in items[0][model.val ()].capacities) {
                    options += '<option value="' + USBType + '"' + (USBType == USBInterface.val () ? ' selected' : '') + '>' + USBType + '</option>';
                }
                USBInterface.html (options);
            } else {
                USBInterface.html ('');
            }
            //capacity value: 2GB/4GB/....
            var capacity = $('.capacity > select', currentRow);
            if (USBInterface.val ()) {
                var options = '';
                for (var cap in items[0][model.val ()].capacities[USBInterface.val ()]) {
                    var v = items[0][model.val ()].capacities[USBInterface.val ()][cap];
                    options += '<option value="' + v + '"' + (v == capacity.val () ? ' selected' : '') + '>' + v + '</option>';
                }
                capacity.html (options);
            } else {
                capacity.html ('');
            }
            //color
            var color = $('.color > select', currentRow);
            if (isModel && type.val ()) {
                var options = '';
                for (var c in items[type.val ()][model.val ()].colors) {
                    var v = items[type.val ()][model.val ()].colors[c];
                    options += '<option value="' + v + '"' + (v == color.val () ? ' selected' : '') + '>' + items.translations[v] + '</option>';
                }
                color.html (options);
            } else {
                color.html ('');
            }
        }
        function itemChange (node)
        {
            $(node).change (function (_e) {
                var index = $(this).closest ('.item-row').index ();
                updateOptions (index);
            });
        }
        $(function (e) {
            updateOptions (0);
            itemChange ($('#items .item-row select'));
            dynamicCheck ();
            autocompleteCustomerInfo ();
            quote.common.init ();
            PDFBind ();
            $('#warningDialog button').click (function (e) {
                $('#warningDialog').hide ();
            });
        });
        /**
         * quote main
         */
        var quote = {
            target: null,
            itemTpl: $('#item-tpl .item-row'),
            customer_info: null,
            common: {
                init: function(){
                    /**
                     * operations of item builder
                     */
                    $(document).on('click', '#items .operations .glyphicon', function(event){
                        var $target = $(event.target);
                        var $row = $target.closest('.item-row');
                        var action = $target.data('action');
                        switch(action) {
                            case 'add': 
                                $row.after(quote.itemTpl.clone(true));
                                var index = $row.index () + 1;
                                updateOptions (index);
                                var node = $('#items .item-row')[index];
                                itemChange ($('select', node));
                                break;
                            case 'copy':
                                $row.after($row.clone(true));
                                break;
                            case 'remove':
                                if ($('#items .item-row').length > 1) {
                                    $row.detach();
                                } else {
                                    alert('One item at least!');
                                }
                                break;
                            default:
                                // do nothing
                        };
                    });
                }
            }
        };

        function submitCheck ()
        {
            var isOK = true;
            $('.required').each (function (index) {
                if ('item-tpl' == $(this).closest ('table').attr('id')) return; 
                if ($(this).val().trim ().length < 1) {
                    $(this).parent ().siblings ('.error').removeClass ('invisiable');
                    isOK = false;
                } else {
                    $(this).parent ().siblings ('.error').addClass ('invisiable');
                }
            });
            return isOK;
        }

        function dynamicCheck ()
        {
            $('.required').on ('data change blur', function (e) {
                if ('item-tpl' == $(this).closest ('table').attr('id')) return; 
                if ($(this).val().trim ().length < 2) {
                    $(this).parent ().siblings ('.error').removeClass ('invisiable');
                    isOK = false;
                } else {
                    $(this).parent ().siblings ('.error').addClass ('invisiable');
                }
            });
        }

        function getCustomerInfo ()
        {
            var customerInfoKey = ['customer_addr', 'customer_name', 'customer_currency', 'customer_phone',
                                   'customer_language', 'customer_email', 'customer_level'
                ];
            var customerInfo = {};
            for (var i = 0; i < customerInfoKey.length; ++i) {
                var v = $('#' + customerInfoKey[i]).val ();
                if (!v.length) {
                    return false;
                }
                customerInfo[customerInfoKey[i]] = v;
            }
            return customerInfo;
        }

        function getItems ()
        {
            var allItems = $('.item-row');
            var items    = [];
            for (var i = 0; i < allItems.length - 1; ++i) {
                var itemRow = {};
                var item = $('select, input', $(allItems[i]));
                for (var j = 0; j < item.length; ++j) {
                    itemRow[$(item[j]).attr('name')] = $(item[j]).val ();
                }
                items.push (itemRow);
            }
            return items;
        }

        function json2URIEncode (json, keyPre, keySuffic)
        {
            var uriEncode = '';
            for (var k in json) {
                uriEncode += keyPre + k + keySuffic + '=' + encodeURIComponent (json[k]) + '&';
            }
            return uriEncode.replace (/&\s*$/, '');
        }

        function buildPostData ()
        {
            var customerInfo = getCustomerInfo ();
            var items        = getItems ();
            var postString   = json2URIEncode (customerInfo, '', '');
            for (var i = 0; i < items.length; ++i) {
                var pre = 'items[' + i + '][';
                postString += '&' + json2URIEncode (items[i], pre, ']');
            }
            return postString;
        }

        function getCustomerIDByField (field, fieldValue)
        {
            var ids = [];
            for (var id in candidates) {
                if (fieldValue == candidates[id][field]) {
                    ids.push (id);
                }
            }
            if (1 == ids.length) return ids[0];
            else return false;
        }

        function setCustomerInfoByID (cid)
        {
            $('[id^=customer_]').each (function (index) {
                var id = $(this).attr('id');
                var oldV = $(this).val ();
                $(this).val (candidates[cid][id]);
                if (oldV != candidates[cid][id]) {
                    $(this).trigger ('data');
                }
            });
        }

        function autocompleteCustomerInfo ()
        {
            var customerIDs  = Object.keys (candidates); 
            var customerAddrs= [];
            var customerNames= [];
            var customerPhones= [];

            for (var id in candidates) {
                if (-1 == customerAddrs.indexOf (candidates[id].customer_addr)) {
                    customerAddrs.push (candidates[id].customer_addr);
                }
                if (-1 == customerNames.indexOf (candidates[id].customer_name)) {
                    customerNames.push (candidates[id].customer_name);
                }
                if (-1 == customerPhones.indexOf (candidates[id].customer_phone)) {
                    customerPhones.push (candidates[id].customer_phone);
                }
            }
            $('#customer_id').autocomplete ({source: Object.keys (candidates)});
            $('#customer_addr').autocomplete ({source: customerAddrs});
            $('#customer_name').autocomplete ({source: customerNames});
            $('#customer_phone').autocomplete ({source: customerPhones});

            $('[id^=customer_]').on ('change blur', function (e) {
                var id = $(this).attr ('id');
                var cid = getCustomerIDByField (id, $(this).val ());
                if (false !== cid) {
                    setCustomerInfoByID (cid);
                }
            });
        }

        function PDFBind ()
        {
            $('#generatePDF').click (function (e) {
                if (!submitCheck ()) {
                    $('#warningDialog').show ();
                    return false;
                }
                $.ajax ({url: '/item_builder?action=save',
                        type: 'POST',
                        data: buildPostData (),
                        dataType: 'json',
                        success: function (response) {
                            if (response.success) {
                                var PDFUrl= window.location.origin + '/pdf/gen.php?uri=' + window.location.origin + '/item_builder?form_id=' + response.data;
                                window.open (PDFUrl);
                                //window.opener.postMessage('QUOTE_TOOL_MESSAGE:Flashbay_quote.pdf|||http://www.flashbay.de/gen.php?uri=' + response.data, 'https://zimbra.flashbay.mars');
                                //window.close();
                            } else {
                                $('#warning-txt').text (response.message);
                                $('#warningDialog').show ();
                            }
                        }
                });	
            });
        }
    </script>
</body>
</html>
