<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>quote tool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script src="/components/internal_tools/netsuite/quote_tool/js/jquery.editable.js"></script>
    <script src="/components/internal_tools/netsuite/quote_tool/js/list.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="/components/internal_tools/netsuite/quote_tool/css/main.css?20150316">
</head>
<body>
    <div class="container" style="padding-top:20px;">
        <!-- sales & customer info -->
        <div class="panel">
            <div class="panel-heading">Customer information</div>
            <div class="panel-body">
                <form action="" class="quote-form form-horizontal">
                    <div class="form-group">
                        <div class="nopdf">
                            <label for="" class="control-label col-sm-2">
                                Customer ID
                            </label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Customer Address</label>
                            <div class="col-sm-9">
                                <textarea name="" id="" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Contact Name</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control">
                            </div>
                        </div>

                        <div class="">
                            <label for="" class="control-label col-sm-2 col-sm-offset-1">Currency</label>
                            <div class="col-sm-3">
                                <select name="" id="" class="form-control">
                                    <option value="">option</option>
                                    <option value="">option</option>
                                    <option value="">option</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Phone</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control">
                            </div>
                        </div>

                        <div class="">
                            <label for="" class="control-label col-sm-2 col-sm-offset-1">
                                Language
                            </label>
                            <div class="col-sm-3">
                                <select name="" id="" class="form-control">
                                    <option value="">option</option>
                                    <option value="">option</option>
                                    <option value="">option</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <label for="" class="control-label col-sm-2">Email</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        
                        <div class="">
                            <label for="" class="control-label col-sm-2 col-sm-offset-1">Price Level</label>
                            <div class="col-sm-3">
                                <select name="" id="" class="form-control">
                                    <option value="">option</option>
                                    <option value="">option</option>
                                    <option value="">option</option>
                                </select>
                            </div>
                        </div>
                    </div>                
                </form>
            </div>
        </div>
        
        <!-- item builder -->
        <div class="panel">
            <!-- <div class="panel-heading">item builder</div> -->
            <table class="quote-builder table">
                <thead>
                    <tr>
                        <th class="item">Type</th>
                        <th>Model</th>
                        <th>Interface</th>
                        <th>Capacity</th>
                        <th>Color</th>
                        <th>Unit Price</th>
                        <th>Tax Rate</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="items">
                    <tr class="item-row">
                        <td class="type">
                            <select name="" id="" class="form-control">
                                <option value="">Model</option>
                                <option value="">Accessory</option>
                                <option value="">Service</option>
                            </select>
                        </td>
                        <td class="model">
                            <select name="" id="" class="form-control">
                                <option value="">Classic</option>
                                <option value="">Twister</option>
                                <option value="">Wafer</option>
                                <option value="">Kinetic</option>
                            </select>
                        </td>
                        <td class="interface">
                            <select name="" id="" class="form-control">
                                <option value="">USB2.0</option>
                                <option value="">USB3.0</option>
                            </select>
                        </td>
                        <td class="capacity">
                            <select name="" id="" class="form-control">
                                <option value="">2GB</option>
                                <option value="">4GB</option>
                                <option value="">8GB</option>
                                <option value="">16GB</option>
                                <option value="">32GB</option>
                            </select>
                        </td>
                        <td class="color">
                            <select name="" id="" class="form-control">
                                <option value="">Black</option>
                                <option value="">White</option>
                                <option value="">Blue</option>
                                <option value="">Black</option>
                            </select>
                        </td>
                        <td class="price" data-pattern="^(\d+)(\.\d+)?$">
                            <input type="text" class="form-control">
                        </td>
                        <td class="taxRate">
                            <input type="text" class="form-control">
                        </td>
                        <td class="operations">
                            <a href="#" class="glyphicon glyphicon-plus" data-action="add"></a>
                            <a href="#" class="glyphicon glyphicon-trash" data-action="remove"></a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <!-- item template -->
            <table id="item-tpl" class="hide">
                <tr class="item-row">
                    <td class="type">
                        <select name="" id="" class="form-control">
                            <option value="">Model</option>
                            <option value="">Accessory</option>
                            <option value="">Service</option>
                        </select>
                    </td>
                    <td class="model">
                        <select name="" id="" class="form-control">
                            <option value="">Classic</option>
                            <option value="">Twister</option>
                            <option value="">Wafer</option>
                            <option value="">Kinetic</option>
                        </select>
                    </td>
                    <td class="interface">
                        <select name="" id="" class="form-control">
                            <option value="">USB2.0</option>
                            <option value="">USB3.0</option>
                        </select>
                    </td>
                    <td class="capacity">
                        <select name="" id="" class="form-control">
                            <option value="">2GB</option>
                            <option value="">4GB</option>
                            <option value="">8GB</option>
                            <option value="">16GB</option>
                            <option value="">32GB</option>
                        </select>
                    </td>
                    <td class="color">
                        <select name="" id="" class="form-control">
                            <option value="">Black</option>
                            <option value="">White</option>
                            <option value="">Blue</option>
                            <option value="">Black</option>
                        </select>
                    </td>
                    <td class="price" data-pattern="^(\d+)(\.\d+)?$">
                        <input type="text" class="form-control">
                    </td>
                    <td class="taxRate">
                        <input type="text" class="form-control">
                    </td>
                    <td class="operations">
                        <a href="#" class="glyphicon glyphicon-plus" data-action="add"></a>
                        <a href="#" class="glyphicon glyphicon-trash" data-action="remove"></a>
                    </td>
                </tr>
            </table>
        </div>

        <div class="quote-footer">
            <a href="#" id="generatePDF" class="btn btn-primary btn-lg btn-generate">Generate PDF</a>
        </div>
    </div>

    <script>
        /**
         * quote main
         */
        var quote = {
            target: null,
            itemTpl: $('#item-tpl .item-row'),
            customer_info: null,
            common: {
                init: function(){
                    quote.common.sortable();
                    quote.common.editable();
                    quote.common.getCustomerInfo();

                    /**
                     * operations of item builder
                     */
                    $(document).on('click', '#items .operations .glyphicon', function(event){
                        var $target = $(event.target);
                        var $row = $target.closest('.item-row');
                        var action = $target.data('action');
                        switch(action) {
                            case 'add': 
                                $row.after(quote.itemTpl.clone(true));
                                break;
                            case 'copy':
                                $row.after($row.clone(true));
                                break;
                            case 'remove':
                                if ($('#items .item-row').length > 1) {
                                    $row.detach();
                                } else {
                                    alert('One item at least!');
                                }
                                break;
                            default:
                                // do nothing
                        };
                    });

                    /**
                     * init popover & tooltip
                     */
                    $('[data-toggle="popover"]').popover({
                        placement: 'bottom',
                        trigger: 'focus hover'
                    });
                    $('[data-toggle="tooltip"]').tooltip();
                },
                getCustomerInfo: function(){
                    $.ajax({
                        url: 'http://beta.flashbay.com/item_builder?action=list_addr',
                        type: 'GET',
                        dataType: 'json',
                        async: false,
                        success: function(response){
                            if (response.success) {
                                quote.customer_info = response.data;
                                return response.data;
                            } else {
                                alert('Can\'t get customer info');
                            };
                        }
                    });
                },
                updateCustomerInfo: function(id){
                    var info = quote.customer_info[id];
                    $customer_addr = $('#customer_addr').text(info.customer_addr);
                    $contact_name = $('#contact_name').text(info.contact_name);
                    $customer_phone = $('#customer_phone').text(info.customer_phone);
                },
                contextmenu: function(){
                    $('[data-toggle="context"]').contextmenu({
                        target: '#context-menu',
                        onItem: function(context, event) {
                            var action = $(event.target).data('action');
                            switch(action) {
                                case 'add': 
                                    $(context).after(quote.itemTpl.clone(true));
                                    
                                    // init for the new row
                                    $('.editable').unbind();
                                    quote.common.editable();
                                    $('[data-toggle="context"]').unbind();
                                    quote.common.contextmenu();

                                    break;
                                case 'copy':
                                    $(context).after($(context).clone(true));

                                    // init for the new row
                                    $('.editable').unbind();
                                    quote.common.editable();
                                    $('[data-toggle="context"]').unbind();
                                    quote.common.contextmenu();

                                    break;
                                case 'remove':
                                    if ($('#items [data-toggle="context"]').length > 1) {
                                        $(context).detach();
                                    } else {
                                        alert('One item at least!');
                                    }
                                    break;
                                default:
                                    // do nothing
                            };
                        }
                    });
                },
                sortable: function(){
                    $( "#items" ).sortable();
                    $( "#items" ).disableSelection();
                },
                editable: function(){
                    $('.editable').editable({
                        className: 'form-control'
                    }, function(e){
                        var target = e.target;
                        var reg = new RegExp(target.data('pattern'));
                        if (e.value.match(reg)) {
                            console.log(e.value);
                            if (target.parent('.item-row').length) quote.common.calculate(target);
                            if (target.attr('id') === 'customer_id') quote.common.updateCustomerInfo(e.value);
                        } else {
                            console.log(e.value);
                            target.text(e.old_value);
                        };
                    });
                },
                calculate: function($trigger){
                    var $row = $trigger.parent('.item-row');
                    var $quantity = $row.children('.quantity');
                    var $price = $row.children('.price');
                    var $amount = $row.children('.amount');
                    var $taxRate = $row.children('.taxRate');
                    var $tax = $row.children('.tax');
                    var $gross = $row.children('.gross');
                    
                    // 保留两位小数
                    var q = parseInt($quantity.text());
                    var p = parseFloat($price.text());
                    var a = parseFloat((q*p).toFixed(2));
                    var tr = parseFloat($taxRate.text())/100;
                    var t = parseFloat((tr*a).toFixed(2));
                    var g = (a + t).toFixed(2);
                    
                    $amount.html(a);
                    $tax.html(t);
                    $gross.html(g);
                },
                addTarget: function(elem){
                    var $elem    = $(elem);
                    var type     = $elem.text();
                    var usb      = $elem.parent('td').siblings('.usb').text();
                    var capacity = $elem.parent('td').siblings('.capacity').text();
                    var color    = $elem.parent('td').siblings('.color').text();

                    usb = usb ? '.'+usb : '';
                    capacity = capacity ? '.'+capacity : '';
                    color = color ? '.'+color : '';

                    $(quote.target).text(type+usb+capacity+color);

                    $('#item-modal').modal('hide');
                },
                getColors: function(a, t){
                    var results = [];
                    for (var i = 0, l = a.length; i < l; i++) {
                        results.push(t[a[i]]);
                    };
                    return results;
                },
                getColorOptions: function($o, t){
                    for ( i in t) {
                        var color = t[i];
                        $o.append('<option value="'+ color +'">'+ color +'</option>');
                    }
                }
            },
            models: {
                init: function(obj){
                    var models = obj.models || {};
                    var translations = obj.translations || {};

                    quote.common.getColorOptions($('#model-color'), translations);

                    // list.js
                    var options = quote.models.options;
                    var values = [];
                    $.each( models, function(i, v){
                        var type       = v.name;
                        var priceRange = quote.models.getPriceRange(v.prices);
                        var capacities = v.capacities;
                        var colors     = quote.common.getColors(v.colors, translations);

                        // 生成filter
                        $('#model-type').append('<option value="'+ type +'">'+ type +'</option>');

                        // 遍历USB
                        for ( u in capacities) {
                            var capacity = capacities[u];
                            if (!!capacity[0]) {
                                // 遍历capacity
                                for ( ca in capacity ) {
                                    // 遍历colors
                                    for ( co in colors) {
                                        values.push({type: type, usb: u, capacity: capacity[ca], color: colors[co], price: priceRange});
                                    }
                                }
                            }
                        }
                    });
                    var modelList = new List('model', options, values);

                    // filters for models
                    $('#model select').change(function () {
                        var type     = $('#model-type').val();
                        var usb      = $('#model-usb').val();
                        var capacity = $('#model-capacity').val();
                        var color    = $('#model-color').val();

                        // filter items in the list
                        modelList.filter(function (item) {
                            if ((item.values().type == type || type == 'all') && (item.values().usb == usb || usb == 'all') && (item.values().capacity == capacity || capacity == 'all') && (item.values().color == color || color == 'all')) {
                                return true;
                            } else {
                                return false;
                            }
                        });
                    });
                },
                getPriceRange: function(o){
                    var o = o || {};
                    return (o.min && o.min.formatted) + ' ~ ' + (o.max && o.max.formatted);
                    // return (o.min && o.min.formatted) + ' ~ ' + (o.max && o.max.formatted) + '<a tabindex="0" role="button" data-toggle="popover" title="Price Table" data-content="Price Table"> <i class="glyphicon glyphicon-question-sign"></i></a>';
                },
                getPriceTable: function(){

                },
                options: {
                    valueNames: ['type', 'usb', 'capacity', 'color', 'price']
                }
            },
            accessories: {
                init: function(obj){
                    var accessories = obj.accessories || {};
                    var translations = obj.translations || {};

                    quote.common.getColorOptions($('#accessory-color'), translations);

                    var options = quote.accessories.options;
                    
                    var values = [];
                    $.each( accessories, function(i, v){
                        var type = v.name;
                        var price = v.price.formatted;
                        var colors = quote.common.getColors(v.colors, translations);

                        // 生成filter
                        $('#accessory-type').append('<option value="'+ type +'">'+ type +'</option>');

                        // 遍历colors
                        for ( co in colors) {
                            values.push({type: type, color: colors[co], price: price});
                        }
                    });

                    var accessoryList = new List('accessory', options, values);

                    // filters for accessories
                    $('#accessory select').change(function () {
                        var type = $('#accessory-type').val();
                        var color = $('#accessory-color').val();

                        // filter items in the list
                        accessoryList.filter(function (item) {
                            if ((item.values().type == type || type == 'all') && (item.values().color == color || color == 'all')) {
                                return true;
                            } else {
                                return false;
                            }
                        });
                    });
                },
                options: {
                    valueNames: ['type', 'color', 'price']
                }
            },
            services: {
                init: function(obj){
                    var services = obj.services || {};
                    var translations = obj.translations || {};

                    var options = quote.services.options;

                    var values = [];
                    $.each( services, function(i, v){
                        var type = v.name;
                        var price = v.price.formatted;

                        // 生成filter
                        $('#service-type').append('<option value="'+ type +'">'+ type +'</option>');

                        values.push({type: type, price: price});
                    });

                    var serviceList = new List('service', options, values);
                },
                options: {
                    valueNames: ['type', 'price']
                }
            }
        };

        $(document).ready(function() {

            // init
            quote.common.init();

        });
        function PDFBind ()
        {
            $('#generatePDF').click (function (e) {
                $('.nopdf').remove ();
                var html = document.documentElement;
                $.ajax ({url: '/item_builder?action=save',
                        type: 'POST',
                        data: 'page=' + window.encodeURIComponent (html),
                        dataType: 'json',
                        success: function (response) {
                            if (response.success) {
                                window.opener.postMessage('QUOTE_TOOL_MESSAGE:Flashbay_quote.pdf|||http://www.flashbay.de/gen.php?uri=' + response.data, 'https://zimbra.flashbay.mars');
                                window.close();
                            } else {
                                alert ('Failed to generate PDF');
                            }
                        }
                });	
            });
        }
        PDFBind ();
    </script>
</body>
</html>
