<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quote tool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="http://beta.flashbay.de/components/internal_tools/netsuite/quote_tool/css/main.css">
</head>
<body style="background-color: #FFF;" class="pdfView">
    <div class="container">
        <!-- logo -->
        <div class="quote-header">
            <div class="row">
                <div class="col-xs-6">
                    <img style="height:90px" alt="Flashbay" border="0" src="https://www.flashbay.com/templates/images/flashbay_logo_us.jpg">
                </div>
                <div class="col-xs-6"></div>
                <div class="clearfix"></div>
            </div>
        </div>

        <!-- sales & customer info -->
        <form action="" class="form-horizontal quote-form">
            <div class="form-group">
                <div class="">
                    <label for="" class="control-label col-xs-2">Company Address</label>
                    <div class="col-xs-4">
                        <p class="form-control-static" data-type="textarea">
                            <?php echo $translatorInst -> getTranslationByName ('_FLASHBAY_ADDRESS');?>
                        </p>
                    </div>
                </div>

                <div class="">
                    <label for="" class="control-label col-xs-2">Customer Address</label>
                    <div class="col-xs-4">
                        <p class="form-control-static" data-type="textarea">
                            <?php echo nl2br (preg_replace ("#\n+#", "\n", strip_tags ($quoteFormCustomerInst -> getAddress ()))); ?>
                        </p>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="">
                    <label for="" class="control-label col-xs-2">Created By</label>
                    <div class="col-xs-4">
                        <p class="form-control-static"><?php echo $quoteFormSalesInst -> getName ();?></p>
                    </div>
                </div>

                <div class="">
                    <label for="" class="control-label col-xs-2">Contact Name</label>
                    <div class="col-xs-4">
                        <p class="form-control-static"><?php echo $quoteFormCustomerInst -> getContact ();?></p>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="">
                    <label for="" class="control-label col-xs-2">Phone</label>
                    <div class="col-xs-4">
                        <p class="form-control-static"><?php echo $quoteFormSalesInst -> getPhone ();?></p>
                    </div>
                </div>

                <div class="">
                    <label for="" class="control-label col-xs-2">Phone</label>
                    <div class="col-xs-4">
                        <p class="form-control-static"><?php echo $quoteFormCustomerInst -> getPhone ();?></p>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="">
                    <label for="" class="control-label col-xs-2">Email</label>
                    <div class="col-xs-4">
                        <p class="form-control-static"><?php echo $quoteFormSalesInst -> getEmail ();?></p>
                    </div>
                </div>

                <div class="">
                    <label for="" class="control-label col-xs-2">Email</label>
                    <div class="col-xs-4">
                        <p class="form-control-static"><?php echo $quoteFormCustomerInst -> getEmail ();?></p>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="">
                    <label for="" class="control-label col-xs-2">Created Date</label>
                    <div class="col-xs-4">
                        <p class="form-control-static"><?php echo date ('m/d/Y', strtotime ($quoteFormInst -> getCreatedTime ()));?></p>
                    </div>
                </div>

                <div class="">
                    <label for="" class="control-label col-xs-2">Price Level</label>
                    <div class="col-xs-4">
                        <p class="form-control-static" data-type="select" data-choice="">
                            <?php echo $priceLevels[$quoteFormCustomerInst -> getLevel ()];?>
                        </p>
                    </div>
                </div>
            </div>
            
            <div class="form-group">
                <div class="">
                    <label for="" class="control-label col-xs-2"></label>
                    <div class="col-xs-4">
                        
                    </div>
                </div>
                <!--
                <div class="">
                    <label for="" class="control-label col-xs-2">Currency</label>
                    <div class="col-xs-4">
                        <p class="form-control-static editable" data-type="select" data-choice="">
                            <?php echo $quoteFormInst -> getCurrency ();?>    
                        </p>
                    </div>
                </div>
                -->
            </div>
        </form>
        
        <!-- item builder -->
        <table class="table table-hover table-editable">
            <thead>
                <tr>
                    <th class="item">Item</th>
                    <th>Quantity</th>
                    <th>Unit price</th>
                    <th>Amount</th>
                    <th>Tax rate</th>
                    <th>Tax amount</th>
                    <th>Gross amount</th>
                    <!-- <th>Virtual proof</th> -->
                </tr>
            </thead>
            <tbody id="items">
            <?php
            foreach ($quoteFormInst -> getItems () as $_itemInst) {
                $itemName = '';
                $itemCode = $_itemInst -> getCode ();
                switch ($_itemInst -> getType ()) {
                case QuoteFormItem :: TYPE_MODEL:
                    $productInst = Product :: getByItemCode ($itemCode);
                    $itemName    = $productInst -> getName ()
                                   . ' USB' . $_itemInst -> getInterface () . '.0'
                                   . ' ' . $_itemInst -> getCapacity ()
                                   . ' ' . $translatorInst -> getTranslationByName ($_itemInst -> getColor ());
                    break;
                case QuoteFormItem :: TYPE_ACCESSORY:
                    $itemName      = $translatorInst -> getTranslationByName ('ACCESSORY_' . $itemCode);
                    break;
                case QuoteFormItem :: TYPE_SERVICE:
                    $serviceInst = Solution :: getByItemCode ($itemCode);
                    $itemName    = $translatorInst -> getTranslationByName ($serviceInst->name);
                    break;
                }
            ?>
                <tr data-toggle="context" class="item-row">
                    <td class="item"><?php echo $itemName; ?></td>
                    <td class="quantity" data-pattern="^\d+$"><?php echo $_itemInst -> getQty ();?></td>
                    <td class="price" data-pattern="^(\d+)(\.\d+)?$"><?php echo $currencyInst -> symbolFormat ($_itemInst -> getUnitPrice ());?></td>
                    <td class="amount"><?php echo $currencyInst -> symbolFormat ($_itemInst -> getAmount ());?></td>
                    <td class="taxRate"><?php echo $_itemInst -> getTaxRate () * 100;?>%</td>
                    <td class="tax"><?php echo $currencyInst -> symbolFormat ($_itemInst -> getTax ());?></td>
                    <td class="gross"><?php echo $currencyInst -> symbolFormat ($_itemInst -> getTotal ());?></td>
                </tr>
            <?php
            }
            ?>
                <tr data-toggle="context" class="item-row">
                    <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                </tr>
                <tr data-toggle="context" class="item-row">
                    <td></td><td></td><td></td><td></td>
                    <td colspan="3" class="txt-right"><strong>Subtotal</strong>&nbsp;
                        <?php echo $currencyInst -> symbolFormat ($quoteFormInst -> getSubTotal ());?>
                    </td>
                </tr>
                <tr data-toggle="context" class="item-row">
                    <td></td><td></td><td></td><td></td><td></td>
                    <td colspan="3" class="txt-right"><strong>Tax</strong>&nbsp;
                        <?php echo $currencyInst -> symbolFormat ($quoteFormInst -> getTax ());?>
                    </td>
                </tr>
                <tr data-toggle="context" class="item-row">
                    <td></td><td></td><td></td><td></td>
                    <td colspan="3" class="txt-right"><strong>Grand Total</strong>&nbsp;
                        <?php echo $currencyInst -> symbolFormat ($quoteFormInst -> getTotal ());?>
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- right-click menu -->
        <div id="context-menu">
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="javascript:void(0);" tabindex="-1" data-action="add"><i class="glyphicon glyphicon-plus"></i> Add new row</a>
                </li>
                <li>
                    <a href="javascript:void(0);" tabindex="-1" data-action="copy"><i class="glyphicon glyphicon-duplicate"></i> Copy this row</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="javascript:void(0);" tabindex="-1" data-action="remove"><i class="glyphicon glyphicon-trash"></i> Remove this row</a>
                </li>
            </ul>
        </div>
    </div>

    <!-- click item column -->
    <div class="modal fade" id="item-modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-heading">
                    <ul id="myTab" class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#model" role="tab" id="model-tab" data-toggle="tab" aria-controls="Model" aria-expanded="true">Model</a>
                        </li>
                        <li role="presentation">
                            <a href="#accessory" role="tab" id="accessory-tab" data-toggle="tab" aria-controls="Accessory">Accessory</a>
                        </li>
                        <li role="presentation">
                            <a href="#service" role="tab" id="service-tab" data-toggle="tab" aria-controls="Service">Service</a>
                        </li>
                    </ul>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div id="myTabContent" class="tab-content">
                        <!-- model tab -->
                        <div role="tabpanel" class="tab-pane fade in active" id="model" aria-labelledby="model-tab">
                            <!-- search -->
                            <div class="form-group">
                                <input class="search form-control" placeholder="Search" />
                            </div>
                            
                            <!-- filters -->
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <select name="" id="model-type" class="form-control">
                                        <option value="all">--type--</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <select name="" id="model-usb" class="form-control">
                                        <option value="all">--USB version--</option>
                                        <option value="USB2.0">USB2.0</option>
                                        <option value="USB3.0">USB3.0</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <select name="" id="model-capacity" class="form-control">
                                        <option value="all">--capacity--</option>
                                        <option value="2GB">2GB</option>
                                        <option value="4GB">4GB</option>
                                        <option value="8GB">8GB</option>
                                        <option value="16GB">16GB</option>
                                        <option value="32GB">32GB</option>
                                        <option value="64GB">64GB</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <select name="" id="model-color" class="form-control">
                                        <option value="all">--color--</option>
                                    </select>
                                </div>
                            </div>
                            
                            <!-- main -->
                            <div class="table-wrapper">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Type</th>
                                            <th>USB version</th>
                                            <th>Capacity</th>
                                            <th>Color</th>
                                            <th>Reference price</th>
                                        </tr>
                                    </thead>
                                    <!-- IMPORTANT, class="list" have to be at tbody -->                            
                                    <tbody class="list">
                                        <tr>
                                            <td><a href="javascript:void(0);" class="type"></a></td>
                                            <td class="usb"></td>
                                            <td class="capacity"></td>
                                            <td class="color"></td>
                                            <td class="price"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- accessory tab -->
                        <div role="tabpanel" class="tab-pane fade" id="accessory" aria-labelledby="accessory-tab">
                            <!-- search -->
                            <div class="form-group">
                                <input class="search form-control" placeholder="Search" />
                            </div>
                            
                            <!-- filters -->
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <select name="" id="accessory-type" class="form-control">
                                        <option value="all">--type--</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <select name="" id="accessory-color" class="form-control">
                                        <option value="all">--color--</option>
                                    </select>
                                </div>
                            </div>
                            
                            <!-- main -->
                            <div class="table-wrapper">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Type</th>
                                            <th>Color</th>
                                            <th>Reference price</th>
                                        </tr>
                                    </thead>
                                    <!-- IMPORTANT, class="list" have to be at tbody -->                            
                                    <tbody class="list">
                                        <tr>
                                            <td><a href="javascript:void(0);" class="type"></a></td>
                                            <td class="color"></td>
                                            <td class="price"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <!-- service tab -->
                        <div role="tabpanel" class="tab-pane fade" id="service" aria-labelledby="service-tab">
                            <!-- search -->
                            <div class="form-group">
                                <input class="search form-control" placeholder="Search" />
                            </div>
                            
                            <!-- main -->
                            <div class="table-wrapper">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Type</th>
                                            <th>Reference price</th>
                                        </tr>
                                    </thead>
                                    <!-- IMPORTANT, class="list" have to be at tbody -->                            
                                    <tbody class="list">
                                        <tr>
                                            <td><a href="javascript:void(0);" class="type"></a></td>
                                            <td class="price"></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
